# -*- coding: utf-8 -*-
"""숫자크기비교.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11rHAsqVp74Za67F44XlORjKBHjL-kTTf
"""

A = int(input("첫 번째 숫자: "))
B = int(input("두 번째 숫자: "))

if (A > B):
  print(">")
elif (A < B):
  print("<")
else:
  print("==")

'''
Comment:

Good!
코딩 테스트에서는 input()에 대한 안내 문구를 제거하는 것이 좋습니다.
'''