# -*- coding: utf-8 -*-
"""두 수 연산.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DOW1BBuoPkRcd2raNyfUxmVOqVkJGdQb
"""

A = int(input('첫 번째 숫자 : '))
B = int(input('두 번째 숫자 : '))

print(A + B)
print(A - B)
print(A * B)
print(A // B)
print(A % B)

'''
Comment:

Good!
코딩 테스트에서는 input()에 대한 안내 문구를 제거하는 것이 좋습니다.
'''