# -*- coding: utf-8 -*-
"""숫자크기비교.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11rHAsqVp74Za67F44XlORjKBHjL-kTTf
"""

A = int(input("첫 번째 숫자: "))
B = int(input("두 번째 숫자: "))
if (A > B):
  print(">")
elif (A < B):
  print("<")
else:
  print("==")